### PR TITLE
Upgrade to Manifest V3, reduce errors, tune permissions

### PR DESCRIPTION
**Pull request by funblaster22**
Upgrade manifest v3:
Renamed entries in manifest

Reduce errors:
Add onInstalled listener, which fixes `Unchecked runtime.lastError: Cannot create item with duplicate id ViewImage-SearchByImage`

Tune permissions:
Replace `tabs` with `activeTab` permission, which do longer prompts permission every time

### CODE REVIEW

**Comment by bijij** [comment]
Hi @funblaster22 thanks for doing this, I'll take some time tomorrow to review this, just a note for now this would likely be shipped as v4 since moving manifest version imo is breaking enough. so might be worth changing that once you've got time!

**Comment by funblaster22** [comment]
Ok, I bumped the version but accidently made a merge conflict in the process sorry 😞

**Comment by Saibamen** [comment]
>in in the coming weeks

;)

**Comment by bijij** [comment]
This was manually rebased to handle support for Firefox.
Thanks for this.

**Pull request closed without merging**
