### PR TITLE
Support redesign

### LINKED ISSUE #161: View Image doesnt work in new G Images redesign
Google recently implemented its new site redesign: the rounded edges design and the extension currently does not work.

thanks for the work
image

### PR DESCRIPTION
**Pull request by qsniyg**
Should fix #161 

A number of code-related changes here have also been done to make it easier in the future. I have added comments explaining what various queries are looking for, and the code has been restructured to support both the current design and the redesign. The extension will also continue working if the globe icon ever changes.

### CODE REVIEW

**Comment by bijij** [comment]
this'll go live in the next couple of hours.

**Comment by urboigrego** [comment]
awesome. Thanks!

**Comment by FatOrangutan** [comment]
@bijij Version on AMO is still on 2.0.1.

**Comment by bijij** [comment]
@FatOrangutan Oops, Must have forgotten to update it sorry about that. should be updated in the next couple hours.

**Pull request merged**
